### ISSUE TITLE
Scores format

### ISSUE THREAD

**Issue by natolambert** [stanford-crfm/fmti#1]
Given that some of these may be updated, it may be good to include the scoring documents in markdown, so PRs can track the adjustments better over time?

**Comment by rishibommasani** [comment]
Hi Nathan! Yes, that makes sense to me. We are still figuring out what the most ergonomic process is for long-term maintenance internally, but once we figure that out, we can then get the outputs in a desirable format (markdown seems good) for easier tracking of deltas over time.

**Comment by zhimin-z** [comment]
Yeah, I have the exact suggestion!

**Comment by rishibommasani** [comment]
Should be handled with the transparency reports.
