### ISSUE TITLE
Why these transparency metrics are not the same?

### ISSUE THREAD

**Issue by zhimin-z** [stanford-crfm/fmti#2]
![image](https://github.com/stanford-crfm/fmti/assets/8592144/0f096efc-2ff0-48bd-8777-0679014ec792)
![image](https://github.com/stanford-crfm/fmti/assets/8592144/e00fbf2d-4e6f-4616-9b11-eca67cb94a7b)
It seems the first figure fails to demonstrate all the evaluation metrics.

**Comment by rishibommasani** [comment]
Just seeing this - the first figure is the macro-average over the 13 depicted subdomains (i.e. weights them the same). In contrast, the second figure is micro-average over all 27 subdomains (i.e. weights each subdomain by the number of indicators in it).

**Comment by zhimin-z** [comment]
> Just seeing this - the first figure is the macro-average over the 13 depicted subdomains (i.e. weights them the same). In contrast, the second figure is micro-average over all 27 subdomains (i.e. weights each subdomain by the number of indicators in it).

Thanks for the clarification. I think it is better to mention that in the documentation or paper as well :)
